<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password</name>
   <tag></tag>
   <elementGuidId>7c6bd518-23f6-4447-87c2-3995b0de5c32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#K1663361506186</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter New password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f97a3908-803c-4cca-860b-5ba1828fc66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663361506186</value>
      <webElementGuid>76e05851-c373-4b2a-b002-e0b72c17fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>d2feba07-f42c-47e2-aca4-892bbd321eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_tbxNewPassword</value>
      <webElementGuid>15ec4973-a244-41bd-9b56-ea1b60361f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknSSP42424215PxBorderE3E3E3</value>
      <webElementGuid>6d4ca38f-93a3-44fb-94dc-8f59e70099a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusin</name>
      <type>Main</type>
      <value>onFocusIn</value>
      <webElementGuid>75262e0a-ad0d-4c76-b5f0-3f12c79c7db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusout</name>
      <type>Main</type>
      <value>onFocusOut</value>
      <webElementGuid>23b7a238-effc-4900-a50f-d287435df843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-input</name>
      <type>Main</type>
      <value>onInput</value>
      <webElementGuid>fe0956c0-222f-4c36-aaa2-cba9685053fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>d44b9416-b090-4a70-b714-c0224f509501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>6df6f841-3c8e-4a94-97cb-5fffc7a84c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d275bd77-4bb4-46fc-bff4-df1af62e8a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bda7b78d-a498-4b4a-9863-62cf9c6a4213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>588895cc-acfd-4e0b-8daa-75d63c4e3bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7ef9dbc4-b4ac-40d5-ab27-39685d596a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kplaceholderskin</name>
      <type>Main</type>
      <value>skntbxplaceholder949494</value>
      <webElementGuid>74fa6cf7-02ae-4978-ab11-7b7680705149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter New password</value>
      <webElementGuid>e90f2dcf-f531-44c6-af59-8f9855911192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Enter New password</value>
      <webElementGuid>7640d824-c7ef-4920-abd9-9599947d237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8012072-7ffc-41fb-a6e8-87ecdf5c00ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter New password</value>
      <webElementGuid>d18b5670-f573-4261-940c-827f06e0981b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663361506186&quot;)</value>
      <webElementGuid>e014b0e8-b859-4a40-9e3e-54ac2f803b82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='K1663361506186']</value>
      <webElementGuid>7151fa1b-1ea2-46d7-9ad8-c908b5f5a13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663361506185']/input</value>
      <webElementGuid>0ac0b160-17f2-46d0-9678-92fb7e5f150e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>65b32169-4bb9-4e3b-90fa-a3108b7531ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'K1663361506186' and @type = 'password' and @placeholder = 'Enter New password']</value>
      <webElementGuid>df4f2cf8-46ee-48c4-99b1-12157ce1fade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
