<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Existing Password</name>
   <tag></tag>
   <elementGuidId>de0f5f19-9db9-44f9-95a6-d4e27b49301f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#K1663361506182</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@placeholder,'Enter existing password')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eed0b88-21e7-47dd-a4b0-cf495767fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663361506182</value>
      <webElementGuid>cb24fa3a-5a86-423a-bca8-31c897d6752b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>55653205-c740-4e29-97c7-f0061c959e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_tbxExistingPassword</value>
      <webElementGuid>6098cc80-596e-4de7-ab8a-35062272be16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknSSP42424215PxBorderE3E3E3</value>
      <webElementGuid>78312858-aa70-4c5b-9af8-702399a6de67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusin</name>
      <type>Main</type>
      <value>onFocusIn</value>
      <webElementGuid>408b6719-0d15-48fe-906d-230e5813403f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusout</name>
      <type>Main</type>
      <value>onFocusOut</value>
      <webElementGuid>a99253bd-fd34-4bb0-afeb-2f4dbcb70e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-input</name>
      <type>Main</type>
      <value>onInput</value>
      <webElementGuid>ff812df1-1020-4e1d-a8c6-cc4dca064228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>6d04bc46-65fc-4d6a-9348-b4e41892aace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>d6b86f65-14e1-4ee6-8896-05181fd71b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>645e5b47-582b-4f6f-b91c-d9bb39fbd1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7bed0174-522d-4164-b7b9-5593c9a36ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>69271ba1-8944-4256-95f9-8b0a3fd860e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7079473e-1bc7-4b44-b75f-cc274e7e23cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kplaceholderskin</name>
      <type>Main</type>
      <value>skntbxplaceholder949494</value>
      <webElementGuid>600dbcb4-f6bd-4c9f-881c-e8307a64666d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter existing password </value>
      <webElementGuid>e4104f1d-ade9-4c27-be88-582d5961f7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Enter existing password </value>
      <webElementGuid>32877b1f-c4b7-4204-b9ab-61b17b576f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4747249c-c84a-4502-8d6e-c5b47125b6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter existing password</value>
      <webElementGuid>96eccf1a-702e-42d4-8936-eea57c09509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663361506182&quot;)</value>
      <webElementGuid>9fd4c6a6-ae5f-4260-8f00-68faedc6c189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='K1663361506182']</value>
      <webElementGuid>0d14ff12-05d1-4d27-a320-9dbd5114aee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663361506180']/input</value>
      <webElementGuid>7d4855c6-1b5e-487e-b992-723e674cf2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>501a5428-73e1-49ed-aa9b-d1b6a3824de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'K1663361506182' and @type = 'password' and @placeholder = 'Enter existing password ']</value>
      <webElementGuid>9d55f5d9-f6eb-41f8-bef1-aaa51f86bf85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
