<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password</name>
   <tag></tag>
   <elementGuidId>7416fc3a-8c45-4c78-9ee5-7b0d300dbe8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#K1663361506190</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Re-enter password ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18877445-bc4b-4c07-9464-fac3b1cb5106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663361506190</value>
      <webElementGuid>1c39b1e7-23f6-4731-b7cc-32db7882599b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>91a72a93-7432-46bd-b363-ff8b0cee7891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_tbxConfirmPassword</value>
      <webElementGuid>b25baef2-cd74-462a-a762-8cf23ebe8b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknSSP42424215PxBorderE3E3E3</value>
      <webElementGuid>cce7ad5a-5262-4a01-87c3-70d36f1d88ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusin</name>
      <type>Main</type>
      <value>onFocusIn</value>
      <webElementGuid>784d80f5-6bb9-45d9-a01c-90d47c0b7257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusout</name>
      <type>Main</type>
      <value>onFocusOut</value>
      <webElementGuid>793d7181-52ff-4de6-9ed3-7fbe0bbdfc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-input</name>
      <type>Main</type>
      <value>onInput</value>
      <webElementGuid>f4498681-a08f-40f6-a959-2848ee7c594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>bae98792-f6b3-4b0e-93cc-2f515d37c2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>4cbd1811-1b5b-4d73-b28d-5a4e3ce23a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>178986c4-dfba-4b4d-beab-17f3956dca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>21bd6dfc-1570-474c-b8d2-2ecd75e69ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>cc413598-196d-4021-b42f-58cd7d8ea6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>106acb58-bcd0-4c94-810b-68fbe5d17816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kplaceholderskin</name>
      <type>Main</type>
      <value>skntbxplaceholder949494</value>
      <webElementGuid>0a62cbba-3ca9-4c3e-8b50-3d593c542de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-enter password </value>
      <webElementGuid>407c5fc4-1c1d-48a3-8961-80f2de979ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Re-enter password </value>
      <webElementGuid>e28807f7-9408-4191-ab7a-3b64aa0cef03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4e191587-65cf-40a1-944d-4f695e6f319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Re enter password</value>
      <webElementGuid>e54e2d70-15db-456e-bfa2-ad17f95a578c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663361506190&quot;)</value>
      <webElementGuid>c4d8893f-0775-435e-af99-dc6cc85f3565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='K1663361506190']</value>
      <webElementGuid>f8d6df82-2dab-4be3-b0ed-7defaff6834a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663361506188']/input</value>
      <webElementGuid>6af22909-d153-40c1-b52e-bd6446692125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>1a7a7123-f7e0-44de-a978-d3ffbdf053eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'K1663361506190' and @type = 'password' and @placeholder = 'Re-enter password ']</value>
      <webElementGuid>8157f923-d82d-4392-bb8d-1bbf135820a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
