<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Username  Password</name>
   <tag></tag>
   <elementGuidId>5d6f3001-8972-453b-bcaa-673dd6dfc825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@title='Username &amp; Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663349682018</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3904ee7c-6061-49b9-b427-640ba11c38b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663349682018</value>
      <webElementGuid>6e63e34b-122e-41d1-a81b-c1688ba5b248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9627023d-2fe6-41da-b434-c7f704855e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_lblUsernameAndPassword</value>
      <webElementGuid>e46bdd42-6da5-4a5d-8e4a-7ce0e1e0f280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknLblSSP72727213px</value>
      <webElementGuid>77378ca3-78cd-4984-8943-0db594a41a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Username &amp; Password</value>
      <webElementGuid>e8e06da4-007b-43e4-ace7-720b97865287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>45590899-66cd-445f-b92a-f35ee11fc20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username &amp; Password</value>
      <webElementGuid>f4c5fc58-3bbe-475c-b9a6-36b439ea2a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username &amp; Password</value>
      <webElementGuid>f9ee147c-16c6-4641-a352-c75623841744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663349682018&quot;)</value>
      <webElementGuid>04d6668b-7013-4339-88a6-70f9fe701220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663349682018']</value>
      <webElementGuid>fc121f26-c36d-4e44-9ff2-42a317ed4a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663349682016']/label</value>
      <webElementGuid>ba13e1a5-595c-4a51-97d9-d54ae904bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[2]/following::label[1]</value>
      <webElementGuid>78dea8b4-1303-4ea8-a65f-38cca7def61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[2]</value>
      <webElementGuid>398da277-aca1-4fd7-b597-20a1387ceaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::label[1]</value>
      <webElementGuid>1d8cb61a-9ecf-456c-b5b9-3795df092780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Settings'])[1]/preceding::label[3]</value>
      <webElementGuid>f647f0b0-52ec-4e25-a75b-d2bdfd254e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username &amp; Password']/parent::*</value>
      <webElementGuid>c89e5af4-a993-4456-8890-db4e9c59c827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[5]/label</value>
      <webElementGuid>e24649d2-3cc7-4220-9c23-d9c1dd850cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663349682018' and @title = 'Username &amp; Password' and (text() = 'Username &amp; Password' or . = 'Username &amp; Password')]</value>
      <webElementGuid>d1b25ff8-cc32-4897-8cb1-4aea1008f6ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
