<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Profile Settings</name>
   <tag></tag>
   <elementGuidId>ad24e04c-6d30-4dc3-a20a-75358550ef7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@title='Profile Settings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663349676785</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b9162551-41a6-4c19-9cb9-79acb8e5213e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663349676785</value>
      <webElementGuid>d47cf00e-a789-4961-8fc3-de705a25051d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ba89ea3a-5879-408e-ba1d-9e72b03b0658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>customhamburger_Settings0lblMyAccounts</value>
      <webElementGuid>0ed4b7f1-26a0-4d36-b8a3-a04c8b075880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknLblHamburgerUnSelected</value>
      <webElementGuid>aaf09eac-9c68-4ac1-a459-482b286b349f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Profile Settings</value>
      <webElementGuid>264fe812-87ec-4823-9434-725d3fc055b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>399c79e5-491e-4ce6-96da-ce403989e657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>My Accounts</value>
      <webElementGuid>781ad582-20b0-4f58-8187-c80f9ff07d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile Settings</value>
      <webElementGuid>8ea0e21b-5b0a-4fe4-b87d-437610fa67d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663349676785&quot;)</value>
      <webElementGuid>f9f66742-bbd5-423f-b69a-a893267bef62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663349676785']</value>
      <webElementGuid>b16a6ab7-5e00-4ed5-943f-862abaab20ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663349676784']/label</value>
      <webElementGuid>1ba20a33-c2e7-44b7-9292-1a5aad2cfe61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::label[1]</value>
      <webElementGuid>d88aef8d-9cc2-4318-b0ba-e7a09335beb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rates &amp; Service Fee'])[1]/following::label[3]</value>
      <webElementGuid>50cae68d-67ee-4262-b0ad-61b20dd07d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Settings'])[1]/preceding::label[1]</value>
      <webElementGuid>4b4b9639-fd74-453b-8899-754d493c9ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Settings'])[1]/preceding::label[2]</value>
      <webElementGuid>78269f6a-8075-42bf-9e8c-5e5d82756a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile Settings']/parent::*</value>
      <webElementGuid>07d7b059-dc3c-4632-bdd1-f78f19c2a0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/label</value>
      <webElementGuid>2af8cace-68be-48b6-8b28-d65382d2d5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663349676785' and @title = 'Profile Settings' and (text() = 'Profile Settings' or . = 'Profile Settings')]</value>
      <webElementGuid>60261069-2997-4bb5-9807-d127c56f9f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
