<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Language</name>
   <tag></tag>
   <elementGuidId>0c76bb18-5a25-4aa3-a43b-4d93f2ba5511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@title='Language']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663349682022</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ae055282-85de-4c92-8b03-8b16369152aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663349682022</value>
      <webElementGuid>a5109a85-358f-488f-8ac0-1b350cbb457f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>348f857d-5d00-4442-91a6-62816b903c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_lblChangeLanguage</value>
      <webElementGuid>17a36bb4-4bc5-44a3-8278-9a045688730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknLblSSP72727213px</value>
      <webElementGuid>02af8e0d-21e9-4708-8c56-893a200e62fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>231c5fda-4c0f-4c1a-aaac-373207f558c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f397b8f-1513-4e52-8488-a59381396a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Username &amp; Password</value>
      <webElementGuid>12b343f9-9616-4882-ac52-fdbf21eda3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>9337767c-95e7-4b62-b989-1a06fee4e3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663349682022&quot;)</value>
      <webElementGuid>806d7601-01f9-4535-b5b7-6a981dee35ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663349682022']</value>
      <webElementGuid>04e0e551-fe85-4578-9812-06b05e8f7d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663349682020']/label</value>
      <webElementGuid>0178fbde-6f23-4735-b7c1-7bccbcda046d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username &amp; Password'])[2]/following::label[1]</value>
      <webElementGuid>4d2524c7-062c-41c5-842a-a639691bf44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::label[2]</value>
      <webElementGuid>4cd762c8-e35a-487f-9fcc-f07e9ba8714d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Settings'])[1]/preceding::label[2]</value>
      <webElementGuid>616051aa-e1cf-4850-b050-9ef027d8dc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[4]/preceding::label[3]</value>
      <webElementGuid>68f61955-2312-42c7-9c38-b9e20443b4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Language']/parent::*</value>
      <webElementGuid>5592ea90-84a1-48b3-aece-5b511e5b57c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/label</value>
      <webElementGuid>5e9553f3-773f-4f7b-936d-fdca35ae40e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663349682022' and @title = 'Language' and (text() = 'Language' or . = 'Language')]</value>
      <webElementGuid>3e3f57c0-937d-4677-8427-c772adbf422d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
