<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Continue password change</name>
   <tag></tag>
   <elementGuidId>1d9908d0-68aa-45b0-9ad1-8d30df223728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#K1663361506196</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@title='Continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1b0472e5-5ce8-42c4-b92b-7827957d9a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663361506196</value>
      <webElementGuid>d9cffdf5-90c3-440c-8b03-9e69e8152daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>9c446709-f4a3-47ea-a42a-7329725de85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_btnEditPasswordProceed</value>
      <webElementGuid>5e1b77ec-72b0-4568-a4cf-966b3594a1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middlecenter sknbtnSSPffffff15px0273e3bg sknBtnFocusSSPFFFFFF15Px0273e3-hover</value>
      <webElementGuid>0503138f-fbbd-4635-93ba-e87a210a7271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ec72bfc-b4e8-4454-a1aa-af4a32bf471f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>da4a7403-3c89-4bf6-91fa-481a5d3db585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>562a7d83-0ef3-48b6-bf8f-fd5143b69ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>99efb9f7-e6a6-4421-9c91-65f5dbffe277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>29b95e19-a4af-4338-86d4-77a2777b7562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>044c91bb-f061-42d8-bef8-6f349c6c3cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>8504c08f-229f-417f-bca9-c36900e8aa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663361506196&quot;)</value>
      <webElementGuid>88966e85-87ba-482e-b0c3-4b89ed43e96f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663361506196']</value>
      <webElementGuid>ea227057-4505-4eac-a326-450251098bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663361506193']/label[2]</value>
      <webElementGuid>899e7223-54bb-42a2-bb5b-e06dc38c3edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::label[1]</value>
      <webElementGuid>c7f2aded-1ce0-4ea5-80db-405b72f9bf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password can have up to 4 consecutive repeated characters'])[1]/following::label[2]</value>
      <webElementGuid>64a94295-6a84-4191-bb30-9485f8136773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::label[2]</value>
      <webElementGuid>ff898cd3-bf6e-4fa1-a8ab-b12c5910b0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/preceding::label[3]</value>
      <webElementGuid>aa884265-1be2-4acc-bb5a-e4b41d22499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>ed902afb-65b3-4256-b318-4883eab9c772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]</value>
      <webElementGuid>04bb0837-85a8-4994-a625-c22d58ef300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663361506196' and @title = 'Continue' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>34862ae0-ef2c-4094-8068-49820435a815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
