<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>50946bf6-bd68-42db-92da-76a68c71efe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='K1663686582614']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Hamburger Menu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d950944b-48bc-4e6f-abf3-6b623f1c6538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>9af04b84-a4af-4c0d-83e8-f44748fbb1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6f823cd5-b512-4718-8aa2-2661bcfc32c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ke</name>
      <type>Main</type>
      <value>1663686583528</value>
      <webElementGuid>0b1c1d1f-384b-4b83-b30a-4d73636637e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1663588537041/desktopweb/images/menu_icon.png</value>
      <webElementGuid>7270fb8f-ed68-406a-86e7-466b5c4e6388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hamburger Menu</value>
      <webElementGuid>cc44632f-58a1-46ee-b65f-0606cedfa75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a43c90af-7c1e-4fcd-b983-451e3c492b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663686582614&quot;)/img[1]</value>
      <webElementGuid>c14a34b4-49c0-42db-9816-2835f9430d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663686582614']/img</value>
      <webElementGuid>6cfc5f6f-daf2-461e-a859-ccb4941b8615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hamburger Menu']</value>
      <webElementGuid>326142dd-5257-47bd-a1aa-f12850670e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>0baf1348-81aa-4c77-bb60-1b1e464ae763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1663588537041/desktopweb/images/menu_icon.png' and @alt = 'Hamburger Menu']</value>
      <webElementGuid>81aa3b4f-fbf5-47df-bb01-929676339c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
