<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione el idioma</name>
   <tag></tag>
   <elementGuidId>7973629a-3bef-481f-abb8-cb7882ba6364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='K1663686585417']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663686585417</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e13aa83e-4451-4eaa-939e-316e51817540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663686585417</value>
      <webElementGuid>874d0eb0-9ae3-491a-b472-a12ebf4c8802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0d8f5c71-78c2-49df-982b-ee42bb62f4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_lblSelectLanguage</value>
      <webElementGuid>c237b017-7d66-423e-b751-bea88dbe4147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknSSP72727215Px</value>
      <webElementGuid>08bb175b-99fb-4e58-a7b2-2f241dd2599b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e70f00b2-628a-41ce-bdec-9cfa70708785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Type:</value>
      <webElementGuid>8ce190d0-79ec-4bf1-8ecb-7803f6602d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione el idioma</value>
      <webElementGuid>f16c17ee-627a-47c1-afbe-bdc95f40cfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663686585417&quot;)</value>
      <webElementGuid>df08df1d-1344-488c-8836-d4e611ec3c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663686585417']</value>
      <webElementGuid>cadc93c8-cb1e-4f01-8ea0-76904dfcdfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663686585416']/label</value>
      <webElementGuid>294ccf29-1f54-44d2-8f9d-9ed678eb325e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Idioma'])[1]/following::label[1]</value>
      <webElementGuid>2dd5f719-ea60-43cf-b63a-b8721c8b8bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajustes'])[1]/following::label[2]</value>
      <webElementGuid>5341d106-dc59-4869-9f25-4156bec524cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambio'])[1]/preceding::label[1]</value>
      <webElementGuid>07c4afd9-7766-4412-afc8-ef1ec2bc66e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración de perfil'])[1]/preceding::label[3]</value>
      <webElementGuid>d148f00d-f102-4cfe-93a1-571da8e722fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seleccione el idioma']/parent::*</value>
      <webElementGuid>b99521da-81bc-4aa6-ba6e-ccad41924796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/label</value>
      <webElementGuid>da630350-857c-4a51-9a5b-8899a0ea036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663686585417' and (text() = 'Seleccione el idioma' or . = 'Seleccione el idioma')]</value>
      <webElementGuid>aabaef25-3cfb-49c6-9391-7274745f73a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
