<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EnglishSpanish</name>
   <tag></tag>
   <elementGuidId>1af664b2-69ba-4fc4-bc52-b2ed04f22994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='K1663686585418']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663686585418</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b4b72af-f99a-46df-ac15-bb2f1264423f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663686585418</value>
      <webElementGuid>27413ee7-b6c7-4772-acb0-fcce93a39aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>ListBox</value>
      <webElementGuid>6ae99f3b-9759-4cf8-8672-90bf1db17d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_lbxSelectLanguage</value>
      <webElementGuid>e94d65f5-20d7-410f-83f2-13ede4114786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknlbxalto42424215pxBordere3e3e32pxRadius</value>
      <webElementGuid>23e6eb64-a978-48ca-850e-bb3b47939c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kv</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>37dfc33e-9e14-4ca6-8189-bf96e445c74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-change</name>
      <type>Main</type>
      <value>onChange</value>
      <webElementGuid>b8aa3b2e-d51a-4217-968d-91a7f23bb866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>450a4a95-fd6b-4ebe-950d-99a0cfff5522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnglishSpanish</value>
      <webElementGuid>a3474950-2c3b-4b49-bf49-500a28924a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663686585418&quot;)</value>
      <webElementGuid>1a72057c-366d-49cc-8f14-6e245fa667a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='K1663686585418']</value>
      <webElementGuid>15714b76-85c2-405c-b47a-67fc71c1a054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663686585416']/select</value>
      <webElementGuid>0d1bfecd-24e9-42e7-9cce-f8df4f294b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Language'])[1]/following::select[1]</value>
      <webElementGuid>991d2c45-98be-4ea5-92e4-50c3921136e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>ee39aacc-5c52-4e23-95c6-98f1d776e41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/preceding::select[1]</value>
      <webElementGuid>eb3bf16a-f9cd-455b-8d9d-9bf43fe9dd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::select[1]</value>
      <webElementGuid>31b6fec5-1283-4ba0-a4ef-fad19b7bbb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2b84f10a-60b9-4430-9094-6cbd99912210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'K1663686585418' and (text() = 'EnglishSpanish' or . = 'EnglishSpanish')]</value>
      <webElementGuid>0b2284db-1bb6-4c12-8b04-b1f046deec87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
