<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SAVINGS</name>
   <tag></tag>
   <elementGuidId>e14c06ad-72dd-42a8-b709-cb4b1c8cabd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@aria-label='randomValue'][normalize-space()='SAVINGS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663218218316</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fd0e6056-68e3-4e6a-bb42-f8c5bcf53d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663218218316</value>
      <webElementGuid>9eb658e6-477b-462a-87c3-41fd4054c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>74aba0d5-7a91-4602-9abd-42a6f7824ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmDashboard_advancedFilters_segTypeOfAccounts[0,0]_flxAccountTypeList_lblAccountType2</value>
      <webElementGuid>7c84d77b-8cc5-43a5-a073-477fa358fe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwo</name>
      <type>Main</type>
      <value>K1663218217265</value>
      <webElementGuid>b38e2f62-25e8-493b-beba-d684e8b22555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwi</name>
      <type>Main</type>
      <value>0,0</value>
      <webElementGuid>2583e6cc-6b90-4923-b150-b05fcc9e6110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft lblSSP42424213px</value>
      <webElementGuid>42e1f080-5087-4057-ac95-cacf739f47f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>596a04ec-fb38-4458-af51-f6c64160a7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colcount</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d7c6d062-a2ce-4b11-ba86-638c9b3f40b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-rowindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7f02695d-e912-4854-9360-78ca2bc7d82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>randomValue</value>
      <webElementGuid>4848d7df-6faf-40f3-b7f2-87eb6cb4add8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cfb2c94c-a4e7-4104-ad9c-e4b69e95a9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAVINGS</value>
      <webElementGuid>87310212-b265-49ad-89cb-a34f1d5b4410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663218218316&quot;)</value>
      <webElementGuid>bb343a1d-ccd9-4c18-9b83-1274023ef1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663218218316']</value>
      <webElementGuid>f8c98759-f054-4fbc-a45f-f2db51ce371d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663218218314']/label[2]</value>
      <webElementGuid>a64d920b-e616-4164-80bc-a9c2fe6e2b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[2]/following::label[1]</value>
      <webElementGuid>528d8031-20a1-4306-84cc-3287b242eee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHEQUING'])[2]/following::label[2]</value>
      <webElementGuid>27be6308-5a8b-4377-a694-4d75e04680ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[2]/preceding::label[1]</value>
      <webElementGuid>543fd259-12f8-4011-962c-fe5082b0542d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EQUITY ACCOUNT'])[2]/preceding::label[2]</value>
      <webElementGuid>d47c8de3-9665-4dac-9b2f-3992d58f29cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/label[2]</value>
      <webElementGuid>722ae411-eaf9-46d9-a404-9d4d9b9fd141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663218218316' and (text() = 'SAVINGS' or . = 'SAVINGS')]</value>
      <webElementGuid>341c8069-4a78-4056-aa29-8e8ec87f22c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
