<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CHEQUING</name>
   <tag></tag>
   <elementGuidId>130a322d-d347-409b-a5c0-59579a3e9790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@aria-label='randomValue'][normalize-space()='CHEQUING']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663218218313</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4c8d4a04-abe3-4bf8-b363-fb63a393aaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663218218313</value>
      <webElementGuid>f7927831-f0f9-4acd-886a-ab3d53c1d3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2990dc9e-8b61-4efc-91d4-0879587646e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmDashboard_advancedFilters_segTypeOfAccounts[0,0]_flxAccountTypeList_lblAccountType1</value>
      <webElementGuid>cce81431-afab-40c1-9772-aad630f13e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwo</name>
      <type>Main</type>
      <value>K1663218217265</value>
      <webElementGuid>5b740287-f5f2-4dec-a499-2969ba8e7196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwi</name>
      <type>Main</type>
      <value>0,0</value>
      <webElementGuid>56a7eb8d-2390-479b-9a3a-9e47fd1260d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft lblSSP42424213px</value>
      <webElementGuid>071753d2-a463-4d05-a3d4-43721ae72048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>090da000-aacc-4c88-baf9-5278211d7012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colcount</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4106a544-6a1d-4516-9dc0-389b00db9368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-rowindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a575690f-d449-4e92-9177-dbd528141ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>randomValue</value>
      <webElementGuid>5463615d-f18b-477d-a487-ad62b1d15e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b71058e-780d-423b-ad20-718bc197da57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHEQUING</value>
      <webElementGuid>d412e212-c606-4dbb-8ab8-ab2bcabfb2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663218218313&quot;)</value>
      <webElementGuid>1944f27e-5a50-4a36-bf23-b067e188f470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663218218313']</value>
      <webElementGuid>bd5d8a45-ab3e-484d-b431-811a1e348367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663218218311']/label[2]</value>
      <webElementGuid>8594bd09-5e59-47ab-b946-da44d92e7816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::label[1]</value>
      <webElementGuid>d09f78ff-9e0e-4179-8470-b8f0450d28a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::label[2]</value>
      <webElementGuid>c3869858-f38b-4402-ac62-9af2cf37e127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[2]/preceding::label[1]</value>
      <webElementGuid>fb0b9b1a-01a5-452b-a1d7-d02b5fc8b914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVINGS'])[2]/preceding::label[2]</value>
      <webElementGuid>eb3c611f-d4b5-41be-85b1-0d0db8dc6893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/label[2]</value>
      <webElementGuid>af4f3d14-82f6-47eb-8644-7d75c4406ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663218218313' and (text() = 'CHEQUING' or . = 'CHEQUING')]</value>
      <webElementGuid>7efe745f-8b5d-444e-a91f-9e7b73e98e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
