<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Apply</name>
   <tag></tag>
   <elementGuidId>adf76236-00f7-4f9c-a97d-d4d4892ecbb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Apply']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663219138076</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6dff16a2-9078-4779-b8e1-a43e08aa1dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663219138076</value>
      <webElementGuid>115540a3-d0b6-46f6-9969-81a277a2373d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>c06713e1-55f7-4836-98d4-3b4a566156ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmDashboard_advancedFilters_btnApplyFilter</value>
      <webElementGuid>fef30290-233e-48d5-9a0d-5a2e6e8b8d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middlecenter sknBtnNormalSSPFFFFFF15Px</value>
      <webElementGuid>a4524995-469c-4a6b-bb9a-b44eb9484fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffafac5e-96b7-4156-ba97-e56cc0da6271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>6fc5dfe6-1215-4588-b603-607c6aa70896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>2cd1a14a-a7da-4fd4-b224-83414c867a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f07d16ca-2a49-42da-a8c6-c338c6efdd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>0f260218-fbd8-44d5-81a3-ce34cb89b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663219138076&quot;)</value>
      <webElementGuid>227c0eee-e92e-468e-9f05-34bf6e3ab520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663219138076']</value>
      <webElementGuid>32d617d9-d4d6-4ce5-b173-bdea955bd88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663219138074']/label[2]</value>
      <webElementGuid>4e6ec3c1-dc63-4110-9347-450e9ff9cb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::label[1]</value>
      <webElementGuid>a33eedbe-b50d-4a88-8574-891d364fa736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US$'])[1]/following::label[2]</value>
      <webElementGuid>f74ff357-1624-41dd-88e5-f31658ee90a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quit My Bills'])[1]/preceding::label[1]</value>
      <webElementGuid>ab99bcfb-8938-443a-8261-75b4e719977e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='g'])[2]/preceding::label[2]</value>
      <webElementGuid>097822bf-634c-4fed-993d-a51476b13840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>8510aa5c-9a5a-4ec8-b70a-3540a88d2463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label[2]</value>
      <webElementGuid>2cc89822-5726-4aad-8df5-d6b0d86036d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663219138076' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>f8d7261a-87ea-4c47-a281-a9ea7bee276c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
