<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_u</name>
   <tag></tag>
   <elementGuidId>ac642a1f-89fb-45f4-9b4d-130ab9223cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='K1663219137611']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663219137611</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3c915f55-8f60-43d2-8b09-ec44d22da09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663219137611</value>
      <webElementGuid>c7fd91a0-144c-4f1e-b8ab-66590f246cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2acc11d9-2561-4e98-8a99-30f1f2406e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmDashboard_lblAdvancedFiltersDropdown</value>
      <webElementGuid>9f9019c2-cecd-4fe5-93ba-6209cb6c7bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middlecenter sknLblOLBFontIcons003E7517pxbordere3e3e3</value>
      <webElementGuid>b57d627a-db45-4574-b3ce-1bbd8fdc8441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>3ecf9557-8241-4c75-807a-5880317da837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663219137611&quot;)</value>
      <webElementGuid>a77c1674-a774-4121-9cde-692b17066d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663219137611']</value>
      <webElementGuid>c94e2607-d61c-44fe-9ba6-f90582a4ee83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663219137610']/label</value>
      <webElementGuid>44c6cb83-33e8-4ad8-8293-904dbabbe4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[5]/following::label[1]</value>
      <webElementGuid>48b55074-43d2-42fc-9802-ed83070cbb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::label[2]</value>
      <webElementGuid>73751b3e-5f51-4452-b5d6-a406b69fa547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/preceding::label[1]</value>
      <webElementGuid>823c66d7-86b7-4c74-8181-7953171002cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMMB Bank'])[1]/preceding::label[2]</value>
      <webElementGuid>e3eb2d81-0c8a-4998-832b-d91b98dfdcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='u']/parent::*</value>
      <webElementGuid>32972767-2025-4e0e-8967-f251ed3797ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/label</value>
      <webElementGuid>3cd735a5-e0bb-427d-8865-fc882f617fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663219137611' and (text() = 'u' or . = 'u')]</value>
      <webElementGuid>c7f0331e-18b5-486c-8044-788e40852858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
