<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>a130b0ce-a39a-4ccd-ad8d-c0652a499d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663176351726</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f6e6a3b-ea5c-4299-b86d-2626d650ac83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663176351726</value>
      <webElementGuid>c99a2cdb-15c6-4457-8f37-f0d00315549b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>83bfa9fb-8520-434b-82cf-a607a688cd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmLogin_txtPassword</value>
      <webElementGuid>e33b1471-639f-4644-b98b-66f55b24108e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft textTextBoxes</value>
      <webElementGuid>f8eda0f1-ffc4-433c-abc2-b0e933d2b828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusin</name>
      <type>Main</type>
      <value>onFocusIn</value>
      <webElementGuid>bfe5fde4-c848-464a-a999-33c4c0cd7a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusout</name>
      <type>Main</type>
      <value>onFocusOut</value>
      <webElementGuid>adee3d29-b4b4-41f4-bc03-e00ed68a1479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-input</name>
      <type>Main</type>
      <value>onInput</value>
      <webElementGuid>7b1f7960-844e-466b-8099-880bb8883522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>52cc099c-fb15-4e69-840f-fc8cede774e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>4d6c9fd5-cfa7-4c84-a29e-288f6b2fc645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f8795022-3ebd-4202-87ff-06121c512765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d240fe3b-eed4-49a4-a201-7e6fe88245a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>0ffa05de-ca80-4e91-be90-94eb507147c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0945098f-470c-4f1a-9ce3-eb35a06846ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kplaceholderskin</name>
      <type>Main</type>
      <value>textTextBoxes</value>
      <webElementGuid>ba38e54f-a5af-4913-a1a3-6f0a60cc8052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2ac6295-7ec4-4850-b83e-4139fb0422c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663176351726&quot;)</value>
      <webElementGuid>44089238-90f1-4f11-991e-0caa32053e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='K1663176351726']</value>
      <webElementGuid>bbe1a292-dcaf-48e8-b83b-6500f5d989d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663176351725']/input</value>
      <webElementGuid>db6d5bcd-eff0-46fc-8576-04fe42567e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>f0bd88e9-243f-4ce8-bc8a-d72b9aa66bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'K1663176351726' and @type = 'password']</value>
      <webElementGuid>aedebea7-5977-42af-84f1-3861d0607d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
