<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account Settings from settings (From the Hamburger menu bar)</name>
   <tag></tag>
   <elementGuidId>276ae806-7b60-4eb9-b232-38da53dcfa36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@title='Account Settings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663205368223</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7f455fe4-794a-4281-97b3-8b179c0926f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663205368223</value>
      <webElementGuid>7e4598db-c2cf-4846-ad43-4315eed064ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>346670e6-687e-46f0-b3e2-abba14b920e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>customhamburger_Settings2lblMyAccounts</value>
      <webElementGuid>75794af5-a933-47a2-95ba-4f1d8a928fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknLblHamburgerUnSelected</value>
      <webElementGuid>bb16212a-7e61-4442-a7d3-cdf8c6f07916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account Settings</value>
      <webElementGuid>1f6110d9-5cfc-42ea-a012-e8c6f412a48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>86ecf1c0-a42f-461a-aa12-dbe59052b7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>My Accounts</value>
      <webElementGuid>a79cb20e-3999-425a-8cde-8de3c3e58a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Settings</value>
      <webElementGuid>d6501bdb-cb20-407c-a59f-a939eadb8fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663205368223&quot;)</value>
      <webElementGuid>a0608c84-08c3-4b6b-9b1b-a0f332ba8e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663205368223']</value>
      <webElementGuid>6a25829a-4327-4113-ae7e-48c6dcd5e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663205368222']/label</value>
      <webElementGuid>44b66eda-b3e7-42a6-b9b5-706607ffb86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Settings'])[1]/following::label[1]</value>
      <webElementGuid>cd20d455-f220-4418-b6fb-22f36bd9e127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/following::label[2]</value>
      <webElementGuid>72a7d4ad-d4ee-4f60-b494-c15abf7c2818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Settings'])[1]/preceding::label[1]</value>
      <webElementGuid>ebde8af2-b358-42bb-97d7-44dad1f65bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::label[3]</value>
      <webElementGuid>8177323e-d544-46a3-aeeb-8a3a05f3e7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account Settings']/parent::*</value>
      <webElementGuid>305cb7f6-af63-4e5e-b0de-e32e002360bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[3]/label</value>
      <webElementGuid>914c6b04-304c-4ca9-88b0-2d642d0d1375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663205368223' and @title = 'Account Settings' and (text() = 'Account Settings' or . = 'Account Settings')]</value>
      <webElementGuid>6fd9da6b-0287-43b1-b92b-1426eff1d39a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
