<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrow button on the settings option from the menu bar img_1</name>
   <tag></tag>
   <elementGuidId>93e9430f-5b37-4109-b9b6-f74331f14fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@kwp='customhamburger_SettingsflxAccountsCollapse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663205368210 > img[alt=&quot;Dropdown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>657223ca-6813-4e64-813e-afaeeafe1520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>7f8a5399-97d4-4ba0-b64c-68754a2226e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c251c8cc-e312-4346-bac3-db0c3ea36072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ke</name>
      <type>Main</type>
      <value>1663205368272</value>
      <webElementGuid>9f82c85e-9cca-4a0d-bb96-600ea6d18e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1657029415387/desktopweb/images/arrow_down.png</value>
      <webElementGuid>c783222f-62d0-486d-b071-ccc5d95ebbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dropdown</value>
      <webElementGuid>f319b5db-4c6c-4b90-a8b5-8309c97e4524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c5b3fb3-3b54-427e-b440-9657d29ab2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663205368210&quot;)/img[1]</value>
      <webElementGuid>2e750179-3f34-4cfb-8a0f-6d532e8553e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663205368210']/img</value>
      <webElementGuid>006c43d5-a779-4308-889c-5f3fbdbb9a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Dropdown'])[6]</value>
      <webElementGuid>dce6b562-e198-4e5c-87f3-4c1dc6dc31aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/img</value>
      <webElementGuid>94f1d554-e1ef-430b-83cb-1b6504310d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1657029415387/desktopweb/images/arrow_down.png' and @alt = 'Dropdown']</value>
      <webElementGuid>5bbe40f5-b01c-4c4c-8f4e-b2bb4e75ef75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
