<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hamburger Menu button</name>
   <tag></tag>
   <elementGuidId>331b8de8-f31c-4f70-b395-fda4bf684c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Hamburger Menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Hamburger Menu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>acbb076d-55b3-4611-b01b-c888f9cdb213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>299984d5-5c2f-4f72-bc1c-80945bbc2754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8c0b060a-7c31-4282-a4ad-ff8ca53d4e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ke</name>
      <type>Main</type>
      <value>1663205368262</value>
      <webElementGuid>cf14324a-20b3-4b31-ba91-66e695bd8a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1657029415387/desktopweb/images/menu_icon.png</value>
      <webElementGuid>037bc21c-a689-49ed-a3e1-0dd32b266e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hamburger Menu</value>
      <webElementGuid>003936d2-2451-4f88-874d-e74fd8439b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f235e36-138b-40ad-8637-efde0069d751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663205367316&quot;)/img[1]</value>
      <webElementGuid>0b1d1513-b157-46f6-badb-a24a5b7746ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663205367316']/img</value>
      <webElementGuid>a7ff3173-53e6-4d2b-8d8d-fc97dac836fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hamburger Menu']</value>
      <webElementGuid>0b520afc-68e5-4f2b-a56f-66448adf039c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>f47179b5-3bc4-4895-8c69-86bed1ab730d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://jmmbsit.temenoscloud.com/apps/OnlineBanking/1657029415387/desktopweb/images/menu_icon.png' and @alt = 'Hamburger Menu']</value>
      <webElementGuid>c7f75e98-70dd-4e0a-b19b-07f4d890bc0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
