<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Nickname</name>
   <tag></tag>
   <elementGuidId>a7510d99-47cd-43a5-a766-7cb6ee1c30fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663209147285</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>416f2b88-d0cf-4bd7-b005-00df18b254df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663209147285</value>
      <webElementGuid>923940ac-329d-49f8-a66e-47cfd93c34f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>c2278a93-b726-4a54-ad3c-7105ed4ae122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_tbxAccountNickNameValue</value>
      <webElementGuid>d07a95a4-1a9c-44d4-adaa-f3da6b613d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middleleft sknBB424242tbx15px</value>
      <webElementGuid>590900c9-d9ae-4ef4-823f-1705cd7a31b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusin</name>
      <type>Main</type>
      <value>onFocusIn</value>
      <webElementGuid>22531ed5-80bc-4418-9e86-2a081e063d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-focusout</name>
      <type>Main</type>
      <value>onFocusOut</value>
      <webElementGuid>dc08158d-51c1-46b2-a629-ed5d3b2e09a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-input</name>
      <type>Main</type>
      <value>onInput</value>
      <webElementGuid>eac6e68f-908f-4296-b9ff-ed9bc1f96608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>2ec45925-fe40-41ce-9ebd-1e8cd7f25f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>d5e04ab4-0579-4dfa-ae06-d4417f66c130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f6021e41-f53e-4fdd-8d9d-e5082114cebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ee0c75a-51d4-434a-b72d-206c9aaeffde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2128e391-de6d-42d8-9c67-3ed2d95d6dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85539353-3a40-4a6e-af25-36d5161b0a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>8a08428a-e740-4b93-9f7d-7ad301bef378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1bf89bbb-7a6c-4238-a2fa-9df94857b001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe5f6277-54c7-4c25-a6f6-d07dee03d4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663209147285&quot;)</value>
      <webElementGuid>6645094c-d462-463e-848d-99c782ba215b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='K1663209147285']</value>
      <webElementGuid>fff4edce-3b5e-4ec2-b70f-f89c95b6ad3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663209147283']/input</value>
      <webElementGuid>06ac0b39-6ddc-4937-94ba-98c8406889db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>47f4831c-1972-421d-8ae1-092237278523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'K1663209147285' and @type = 'text']</value>
      <webElementGuid>1a87575e-4b5c-4978-a663-4539a692176b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
