<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Edit(account preferences to edit a displayed account)</name>
   <tag></tag>
   <elementGuidId>ed62af5c-7804-4d71-a6a8-ca5cc9a36b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@title='EDIT'][normalize-space()='Edit'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663205371993</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a5f11687-23ac-4ca6-affa-6fa883e8ff44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663205371993</value>
      <webElementGuid>1cec4734-b4e4-4fde-8813-b8bc03f84ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>7ec83d70-724a-4bc5-946e-8cc89644f6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmProfileManagement_settings_segAccounts[0,0]_flxAccountRow_btnEdit</value>
      <webElementGuid>2cf5f1f5-0366-43f9-a64c-9a9e2a5e16e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwo</name>
      <type>Main</type>
      <value>K1663205370784</value>
      <webElementGuid>7c005c64-f98d-4910-9383-9bf04acf6ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwi</name>
      <type>Main</type>
      <value>0,0</value>
      <webElementGuid>5a425788-7d0b-4ce1-b7e3-b487cd95a1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middlecenter sknBtnSSP0273e313Px</value>
      <webElementGuid>9e97b9ed-f437-48b1-8daa-6c1d299e54fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6414f7d2-0313-46fe-b787-0870190c2ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keydown</name>
      <type>Main</type>
      <value>onKeyDown</value>
      <webElementGuid>0e731071-2dfc-47f1-9daa-749b4af08f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwh-keyup</name>
      <type>Main</type>
      <value>onKeyUp</value>
      <webElementGuid>fde69559-16a3-4068-81f8-d679c9e57113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>b673e8b8-8d92-413c-b4f5-9a4e669b4a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12c9dbe6-f827-4e25-874d-26f8e00cbcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>49e8d510-d25e-44f3-babd-0d903514cac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colcount</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2ba93411-eb61-4d8e-9c7f-114cd595c18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-rowindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>efee12f0-b869-47db-ab96-9104e7053c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>a0ef7eb2-eb4f-413b-b499-caf32bd73fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>5dcba467-b29b-4dd6-ac33-4efcab3951cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663205371993&quot;)</value>
      <webElementGuid>bd257c04-d0ef-4133-8de3-b953ddae8375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663205371993']</value>
      <webElementGuid>9cefae22-39b2-4e91-8c8c-06d042841aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663205371988']/label[2]</value>
      <webElementGuid>5e929bf8-ba1a-4c4a-857d-494eeae3e905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMMB EzAcess'])[1]/following::label[2]</value>
      <webElementGuid>7956d181-c450-4544-aab8-d7c0eb47e3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings Accounts'])[1]/following::label[3]</value>
      <webElementGuid>f7d5ad6e-837f-4c4a-8777-26c15853d449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Holder:'])[1]/preceding::label[1]</value>
      <webElementGuid>8d0689ff-2a60-4edc-8335-21ec1fe07ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMMB EzAcess'])[2]/preceding::label[2]</value>
      <webElementGuid>d3f4b8b8-bb00-4468-825a-eccf22046edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>d208bf56-b83c-410c-95a7-099578e86b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/label[2]</value>
      <webElementGuid>e3d0059c-53e6-4641-aa3c-38c1d7ef4a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663205371993' and @title = 'EDIT' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>d77ac173-8bdc-433e-87d7-b3614b87bea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
