<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sort by account name</name>
   <tag></tag>
   <elementGuidId>c912a17f-099c-495d-b7f7-d6f3a3f61a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@kwp='frmDashboard_advancedFilters_lblIconAccountName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#K1663210874445</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>20811f4f-fdf5-4e25-bd0f-9b9a982e64c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>K1663210874445</value>
      <webElementGuid>888bd7b4-a393-4919-a572-1ccb3daecd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kw</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>12e91d9a-44bf-42e2-a52c-f9c70a569a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwp</name>
      <type>Main</type>
      <value>frmDashboard_lblAdvancedFiltersDropdown</value>
      <webElementGuid>f8ef5689-c659-4706-afd7-a4ec29b5c270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-ca-middlecenter sknLblOLBFontIcons003E7517pxbordere3e3e3</value>
      <webElementGuid>dce78036-cc08-4110-a6c6-83c403926385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>5391118d-3da1-4eef-a4ee-be67a5aec0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K1663210874445&quot;)</value>
      <webElementGuid>124e4476-87b6-476e-97ef-8107f8953ce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='K1663210874445']</value>
      <webElementGuid>e9b0bdfb-0520-4111-84d3-76bd24d1087e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='K1663210874444']/label</value>
      <webElementGuid>b8360ca0-4f12-41ad-bc7d-cdc4f57f2e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[5]/following::label[1]</value>
      <webElementGuid>fc97516e-48f4-4c4e-834e-a663bb3c0d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::label[2]</value>
      <webElementGuid>07e4fdf1-b4bc-49b9-8003-2de8167dfcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/preceding::label[1]</value>
      <webElementGuid>9f5868b8-4415-4ac2-af01-8fdc4b1c33d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMMB Bank'])[1]/preceding::label[2]</value>
      <webElementGuid>b512f706-09ee-4291-a741-b631c07bbf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='u']/parent::*</value>
      <webElementGuid>fa043cda-c835-487e-9ca4-128b0d7b198e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/label</value>
      <webElementGuid>098a6950-f385-4ac6-abb6-7294fb848d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'K1663210874445' and (text() = 'u' or . = 'u')]</value>
      <webElementGuid>06d40826-198f-4cd1-9b6b-76975bacf8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
